import { Flex } from '@chakra-ui/react';
import Head from 'next/head';
import React from 'react';
import Navigation from './Navigation';

const Layout = (props: any) => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Flex
        as="main"
        height="auto"
        flexDirection="column"
        backgroundColor="theming.secondary"
        px={[4, 12, 24, 48]}
      >
        {props.children}
      </Flex>
    </>
  );
};

export default Layout;
