import Head from 'next/head';
import React from 'react';
import Navigation from './Navigation';

const Layout = (props: any) => {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main>{props.children}</main>
    </div>
  );
};

export default Layout;
